@startuml
'https://plantuml.com/class-diagram

class Main {
}
package entities {
class CupcakeBottom {
- final int cupakeBottomId
- final int priceBottom
- final String flavour
- final String cupcakeType;
+ int getCupcakeBottomId()
+ int getPrice()
+ String getFlavour()
+ String getCupcakeType()
'override
+ String toString()
}
class CupcakeTop {
- final int cupcakeTopId
- final int priceTop
- final String flavour
- final String cupcakeType;
+ int getCupcakeTopId()
+ int getPrice()
+ String getFlavour()
+ String getCupcakeType()
'override
+ String toString()
}

class Cupcake {
- int price
- CupcakeTop cupcakeTop
- CupcakeBottom cupcakeBottom
+ Cupcake()
+ CupcakeBottom getCupcakeBottom()
+ CupcakeTop getCupcakeTop()
+ int getPrice()
'override
+ String toString()



}

class User {
- int userId
- String username
- String password
- String role
+ User()
+ int getUserId()
+ String getUsername()
+ String getPassword()
+ String getRole()
}
}

package controllers {
class UserController {
+ static void addRoutes()
- static void createUser()
+ static void login()
- static void logout()

}
class OrderController {
+ static void addRoutes()
- static void addOrder()
- static void showOrder()
- static void removeOrder()

}
}

package persistence {
class OrderMapper {
+ static void newOrder()
+ static Cupcake getOrder()
+ static Cupcake getFavoriteOrder()
+ static void removeOrder()
}

class UserMapper {
+ static User login()
+ static void createUser()
}
}

Main *-- OrderController
OrderController o-- Cupcake
Cupcake *-- CupcakeBottom
Cupcake *-- CupcakeTop
UserController o-- User

@enduml