@startuml
'https://plantuml.com/class-diagram

class Main {
}

package entities {
    enum CupcakeType {
        TOP
        BOTTOM
    }
    class CupcakeFlavour {
        - final int cupakeFlavourId
        - final int price
        - final String flavourName
        - final String flavourDesc
        - final CupcakeType type;
        + int getCupcakeBottomId()
        + int getPrice()
        + String getFlavour()
        + CupcakeType getType()
        + String getCupcakeType()
        'override
        + String toString()
    }

    class Cupcake {
        - CupcakeFlavour top
        - CupcakeFlavour bottom
        + Cupcake(top, bottom)
        + CupcakeFlavour getCupcakeBottom()
        + CupcakeFlavour getCupcakeTop()
        + int getPrice()
        'override
        + String toString()
    }

    class User {
        - int userId
        - String username
        - String password
        - String role
        - int balance
        + User()
        + int getUserId()
        + String getUsername()
        + String getPassword()
        + String getRole()
        + int getBalance()
        + void deposit()
    }

    class Order {
        - int orderId
        - String name
        - LocalDate datePlaced
        - LocalDate datePaid
        - LocalDate dateCompleted
        - String status
        - User user
        - List<OrderLine> orderLines
        + Order()
        + int getOrderId()
        + String getName()
        + LocalDate getDatePlaced()
        + LocalDate getDatePaid()
        + LocalDate getDateCompleted()
        + String getStatus()
        + User getUser()
        + List<OrderLine> getOrderLines()
        + void updateStatus(String)
    }
    class OrderLine {
        - int orderId
        - int quantity
        - Cupcake cupcake
        - int price
        + int getOrderId()
        + int getQuantity()
        + Cupcake getCupcake()
        + int getPrice()
    }
}

package controllers {
    class CupcakeController {
        + static void addRoutes()
        + static void showFrontpage()
    }
    class UserController {
        + static void addRoutes()
        - static void createUser()
        - static void passwordCheck()
        + static void doLogin()
        - static void doLogout()
    }
    class OrderController {
        + static void addRoutes()
        - static void addCupcakeToOrder()
        - static void showOrderHistory()
        - static void deleteOrder()
    }
}

package persistence {
    class CupcakeMapper {
        + static List<CupcakeFlavour> getFlavours()

    }
    class OrderMapper {
        + static void List<Order> getOrders()
        + static CucpakeFlavour getCupcakeFlavour()
        + static void deleteOrder()
    }

    class UserMapper {
        + static void createUser()
        + static void doLogin()

    }
}

package Test {
 class Test {
    + userTestLoginValidLogin()
    + userTestLoginInvalidLogin()
    + orderTestNewOrderValidData()
    + orderTestNewOrderInvalidData()


 }
}

Main -- CupcakeController
Main -- OrderController
Main -- UserController
CupcakeController -- CupcakeMapper
OrderController -- OrderMapper
UserController -- UserMapper
Cupcake *-- CupcakeFlavour
Order *-- OrderLine
Order o-- User
OrderLine *-- Cupcake
CupcakeFlavour *- CupcakeType

@enduml