@startuml
'https://plantuml.com/state-diagram

state c <<choice>>

[*] -> Forside
Forside -> LægIKurv
Forside --> LoginDialog
LoginDialog : submit login info
LoginDialog --> c : Login
c --> LoginDialog : [login incorrect] / show error msg
c --> Authorized : [login correct]
Forside --> SeKurv
SeKurv -> CheckudSomGæst

state Authorized {
    [*] --> SeDinInfo
    SeKurv --> BetalMedBalance
    state Admin {
        [*] --> TilføjFlavour
        [*] --> ToggleFlavour
        [*] --> OrdreHistorik
        OrdreHistorik --> OrdreDetaljer
        OrdreHistorik --> SletOrdre
        [*] --> KundeKartotek
        KundeKartotek --> IncreaseBalance
        KundeKartotek --> KundeDetaljer
        KundeDetaljer --> OrdreDetaljer
    }
}

@enduml